services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_DATABASE=trips
      - POSTGRESQL_PASSWORD=agorasimessasenhavaisersecreta
      - POSTGRESQL_USERNAME=lucasbittencourt
    networks:
      - trips

networks:
  trips:
    driver: bridge
