services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./db:/var/lib/postgresql
    environment:
      - POSTGRESQL_DATABASE="${POSTGRES_DATABASE}"
      - POSTGRESQL_PASSWORD="${POSTGRES_PASSWORD}"
      - POSTGRESQL_USERNAME="${POSTGRES_USERNAME}"
    networks:
      - trips

networks:
  trips:
    driver: bridge

volumes:
  db: